version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: book_manager_db
    environment:
      POSTGRES_DB: book_manager
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
